#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

cd "$OPENSHIFT_REPO_DIR"src/

if test -n "$OPENSHIFT_MYSQL_DB_URL"; then
    mysqldump --verbose --all-databases --triggers --routines --events | gzip -c >  "$OPENSHIFT_DATA_DIR/mysqldump.sql.gz"
else
    pushd "$OPENSHIFT_DATA_DIR"
    for elem in $(ls "*.db"); do
        cp -v "$elem" "${elem}.bak"
    done
    popd
fi

for directory in $(ls); do
    cd $directory
    python setup.py install -f
    cd ..
done
